# Copyright (c) 2010 Joseph D Poirier
# Distributable under the terms of The New BSD License
# that can be found in the LICENSE file.


include $(GOROOT)/src/Make.inc



TARG=lte/l1enc

GOFILES=\
	adhoc.go\
	crc.go\
	blkseg.go\

#	turbointerl.go\
#	encode.go\
#	turboenc.go\



include $(GOROOT)/src/Make.pkg
